import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Basis
import Mathlib.RingTheory.Ideal.Span
--- Needed for Hilbert Basis Theorem
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Finiteness.Defs
import Mathlib.RingTheory.Nullstellensatz
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

noncomputable section

namespace FiniteGenSets
variable {K : Type*} [Field K]
variable {σ : Type*}


def affineVariety (F : Set (MvPolynomial σ K)): Set (σ → K) :=
    {x : σ → K | ∀ p ∈ F, (MvPolynomial.eval x) p = 0}

--- Need a finite indexing set (σ here) for this to be true
theorem hasFiniteGenSet {σ : Type*} [Fintype σ] (I : Ideal (MvPolynomial σ K)):
  ∃ F : Set (MvPolynomial σ K), F.Finite ∧ Submodule.span (MvPolynomial σ K) F = I := by
  have finitely_gen : I.FG := by --- Hilbert Basis theorem holds as MvPolynomial σ K a Noetherian ring
    apply isNoetherian_def.mp
    apply MvPolynomial.isNoetherianRing
  apply Submodule.fg_def.mp --- By definition of being finitely generated it means that I has a finite generating set
  exact finitely_gen


theorem inSpanAffineVarietyGenerators {x : σ → K} (F : Set (MvPolynomial σ K)) (h : x ∈ affineVariety F) :
  ∀ p ∈ Ideal.span F, (MvPolynomial.eval x) p = 0 := by
  intro p hp
  --- This gives us that p ∈ I = <f1,...,fs> means that it is a linear combination of these generators
  have in_span: ∃ (l : ↑F →₀ MvPolynomial σ K), (Finsupp.linearCombination (MvPolynomial σ K) Subtype.val) l = p := by
    apply (Finsupp.mem_span_iff_linearCombination (MvPolynomial σ K) (F) (p)).mp
    exact hp
  rcases in_span with ⟨coeffs, is_lin_comb⟩ --- Extract the coefficients
  subst is_lin_comb
  rw [Finsupp.linearCombination_apply (MvPolynomial σ K) (coeffs)] --- Writes the linear combination as an actual linear combination
  have eval_zero : ∀ f ∈ F, (MvPolynomial.eval x) f = 0 := by
    intro f hf
    apply h
    exact hf
  simp [Finsupp.sum, eval_zero]


theorem basisSameVariety (F G : Set (MvPolynomial σ K)) :
  Ideal.span F = Ideal.span G → affineVariety F = affineVariety G := by
  intro h
  ext x
  constructor
  · intro hx p hp
    apply inSpanAffineVarietyGenerators F hx --- All functions in F vanish at x which implies all functions in ideal generated by F do to
    rw [h] --- As ideals are equal all functions in ideal spanned by G vanish at x
    exact Submodule.mem_span_of_mem hp --- p ∈ G the generating set so vanishes at x
  · intro hx p hp --- Analogus to above
    apply inSpanAffineVarietyGenerators G hx
    rw [← h]
    exact Submodule.mem_span_of_mem hp


theorem isAffineVariety {σ : Type*} [Fintype σ] (I : Ideal (MvPolynomial σ K)):
  ∃ F : Set (MvPolynomial σ K), F.Finite ∧ MvPolynomial.zeroLocus K I = affineVariety F := by
  have fin_gen_set : ∃ f : Set (MvPolynomial σ K), f.Finite ∧ Submodule.span (MvPolynomial σ K) f = I := by
    apply hasFiniteGenSet
  rcases fin_gen_set with ⟨f, fin, span⟩ --- Extract the finite basis
  use f
  constructor
  · exact fin
  · ext x
    constructor
    · intro h p hp --- Get MvPolynomial p that we need to evaluate to 0 at x
      apply h --- Suffices to show it is in the ideal as all functions in here are 0 at x
      subst span --- I = <f1,...,fs> so showing p in the ideal equivalent to showing it is in the set spanned by these fi
      apply Submodule.mem_span_of_mem --- p is actually a member of the generating set and this is by definition in the set spanned
      exact hp
    · intro h p hp
      subst span  --- I = <f1,...,fs>
      apply inSpanAffineVarietyGenerators f h
      exact hp

end FiniteGenSets
