import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Basis
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Finiteness.Defs
import Mathlib.RingTheory.Nullstellensatz
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

noncomputable section

namespace FiniteGenSets
variable {K : Type*} [Field K]
variable {σ : Type*}


def affineVariety (F : Set (MvPolynomial σ K)) : Set (σ → K) :=
  {x : σ → K | ∀ p ∈ F, (MvPolynomial.eval x) p = 0}


@[simp]
theorem memAffineVariety {F : Set (MvPolynomial σ K)} {x : σ → K} :
  x ∈ affineVariety F ↔ ∀ p ∈ F, (MvPolynomial.eval x) p = 0 := by
  rfl


-- Need a finite indexing set (σ here) for this to be true
theorem hasFiniteGenSet [Fintype σ] (I : Ideal (MvPolynomial σ K)):
  ∃ F : Set (MvPolynomial σ K), F.Finite ∧ Submodule.span (MvPolynomial σ K) F = I := by
  have finitely_gen : I.FG := by -- Hilbert Basis theorem holds as MvPolynomial σ K a Noetherian ring
    apply isNoetherian_def.mp
    apply MvPolynomial.isNoetherianRing
  apply Submodule.fg_def.mp -- By definition of being finitely generated it means that I has a finite generating set
  exact finitely_gen


theorem inSpanAffineVarietyGenerators {x : σ → K} (F : Set (MvPolynomial σ K)) (h : x ∈ affineVariety F) :
  ∀ p ∈ Ideal.span F, (MvPolynomial.eval x) p = 0 := by
  intro p hp
  -- This gives us that p ∈ I = <F> means that it is a linear combination of a finite number of these generators
  rw [Finsupp.mem_span_iff_linearCombination] at hp
  rcases hp with ⟨coeffs, is_lin_comb⟩ -- Extract the coefficients
  subst is_lin_comb
  rw [Finsupp.linearCombination_apply (MvPolynomial σ K) (coeffs)] -- Writes the linear combination as an actual linear combination
  simp [Finsupp.sum, memAffineVariety.mp h]


-- This says that for some set F we have that V(F) = V(<F>)
-- First V is affine variety, second is the zero locus of the ideal generated by this set
theorem zeroLocusOfGenSetIsVariety (F : Set (MvPolynomial σ K)) :
  MvPolynomial.zeroLocus K (Ideal.span F) = affineVariety F := by
  ext x
  constructor
  · intro h p hp
    apply h
    apply Ideal.subset_span -- The elements that generate an ideal are members of this ideal generated by them
    exact hp
  · intro h p hp
    apply inSpanAffineVarietyGenerators F h -- If all generators of an ideal vanish at x ∈ σ → K, then so will all elements of the ideal they generate
    exact hp


theorem idealGivesVariety [Fintype σ] (I : Ideal (MvPolynomial σ K)):
  ∃ F : Set (MvPolynomial σ K), F.Finite ∧ MvPolynomial.zeroLocus K I = affineVariety F := by
  rcases hasFiniteGenSet (I) with ⟨F, fin, span⟩ -- Extract the finite basis
  use F
  constructor
  · exact fin
  · subst span
    exact zeroLocusOfGenSetIsVariety F


 -- This says that given any F ⊆ MvPolynomial σ K, V(F) = V(f1,...,fs) for some f1,...,fs ∈ MvPolynomial σ K
theorem onlyFiniteSetsNeeded [Fintype σ] (F : Set (MvPolynomial σ K)) :
  ∃ G : Set (MvPolynomial σ K), G.Finite ∧ affineVariety F = affineVariety G := by
  rw [← zeroLocusOfGenSetIsVariety F]
  rcases idealGivesVariety (Ideal.span F) with ⟨G, fin, h⟩
  use G


theorem basisSameVariety (F G : Set (MvPolynomial σ K)) :
  Ideal.span F = Ideal.span G → affineVariety F = affineVariety G := by
  intro h
  rw [← zeroLocusOfGenSetIsVariety, ← zeroLocusOfGenSetIsVariety]
  congr


end FiniteGenSets
